{"uid":"28785c6ed1ceceda","name":"test_query_unsupported_network[3-3]","fullName":"tests.agent_trajectory.feed_explore#test_query_unsupported_network","historyId":"d0aa82a76381055cce1d53079f03a727","time":{"start":1730346486957,"stop":1730346489062,"duration":2105},"status":"failed","statusMessage":"AssertionError: assert 'Unsupported network' in 'No activities found for the given address.'","statusTrace":"feed_explorer_agent = AgentExecutor(verbose=True, agent=RunnableMultiActionAgent(runnable=RunnableAssign(mapper={\n  agent_scratchpad: Runnab...ys_arg=[], stream_runnable=True), tools=[FeedExecutor(), FeedSourceExecutor(), DeFiExecutor(), TelegramNewsExecutor()])\n\n    @pytest.mark.asyncio\n    async def test_query_unsupported_network(feed_explorer_agent):\n        events = feed_explorer_agent.astream_events(\n            {\"messages\": [HumanMessage(content=\"Show me activities on the XYZ network\", name=\"human\")]}, version=\"v1\"\n        )\n    \n        tool_end_count = 0\n        async for event in events:\n            if event[\"event\"] == \"on_tool_end\":\n                tool_end_count += 1\n                assert \"output\" in event[\"data\"]\n>               assert \"Unsupported network\" in event[\"data\"][\"output\"]\nE               AssertionError: assert 'Unsupported network' in 'No activities found for the given address.'\n\nagent_trajectory/feed_explore.py:89: AssertionError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"event_loop_policy","time":{"start":1730346479173,"stop":1730346479173,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"feed_explorer_agent","time":{"start":1730346479173,"stop":1730346486873,"duration":7700},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop","time":{"start":1730346486873,"stop":1730346486874,"duration":1},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"status":"failed","statusMessage":"AssertionError: assert 'Unsupported network' in 'No activities found for the given address.'","statusTrace":"feed_explorer_agent = AgentExecutor(verbose=True, agent=RunnableMultiActionAgent(runnable=RunnableAssign(mapper={\n  agent_scratchpad: Runnab...ys_arg=[], stream_runnable=True), tools=[FeedExecutor(), FeedSourceExecutor(), DeFiExecutor(), TelegramNewsExecutor()])\n\n    @pytest.mark.asyncio\n    async def test_query_unsupported_network(feed_explorer_agent):\n        events = feed_explorer_agent.astream_events(\n            {\"messages\": [HumanMessage(content=\"Show me activities on the XYZ network\", name=\"human\")]}, version=\"v1\"\n        )\n    \n        tool_end_count = 0\n        async for event in events:\n            if event[\"event\"] == \"on_tool_end\":\n                tool_end_count += 1\n                assert \"output\" in event[\"data\"]\n>               assert \"Unsupported network\" in event[\"data\"][\"output\"]\nE               AssertionError: assert 'Unsupported network' in 'No activities found for the given address.'\n\nagent_trajectory/feed_explore.py:89: AssertionError","steps":[],"attachments":[{"uid":"6da6d5b6790cf94a","name":"stdout","source":"6da6d5b6790cf94a.txt","type":"text/plain","size":192},{"uid":"2498e3cda6f50dbc","name":"stderr","source":"2498e3cda6f50dbc.txt","type":"text/plain","size":302}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":2,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"event_loop::3","time":{"start":1730346489131,"stop":1730346489194,"duration":63},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop::_close_event_loop","time":{"start":1730346489194,"stop":1730346489194,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop::_restore_policy","time":{"start":1730346489194,"stop":1730346489194,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop::_provide_clean_event_loop","time":{"start":1730346489194,"stop":1730346489194,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"tag","value":"asyncio"},{"name":"parentSuite","value":"tests.agent_trajectory"},{"name":"suite","value":"feed_explore"},{"name":"host","value":"fv-az2031-287"},{"name":"thread","value":"3714-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.agent_trajectory.feed_explore"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"__pytest_repeat_step_number","value":"2"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"tags":["asyncio"]},"source":"28785c6ed1ceceda.json","parameterValues":["2"]}