{"name": "test_swap_eth_to_usdt[3-3]", "status": "broken", "statusDetails": {"message": "pydantic_core._pydantic_core.ValidationError: 1 validation error for ParamSchema\nto_chain\n  Input should be 'ETH', 'BSC', 'ARBITRUM', 'OPTIMISM' or 'POLYGON' [type=literal_error, input_value='eth', input_type=str]\n    For further information visit https://errors.pydantic.dev/2.8/v/literal_error", "trace": "asset_management_agent = AgentExecutor(verbose=True, agent=RunnableMultiActionAgent(runnable=RunnableAssign(mapper={\n  agent_scratchpad: Runnab...rg=[], stream_runnable=True), tools=[SwapExecutor(), TransferExecutor(), TokenBalanceExecutor(), NFTBalanceExecutor()])\n\n    @pytest.mark.asyncio\n    async def test_swap_eth_to_usdt(asset_management_agent):\n        events = asset_management_agent.astream_events({\"messages\": [HumanMessage(content=\"Can you swap 20 eth to usdt ?\", name=\"human\")]}, version=\"v1\")\n    \n        on_tool_end_count = 0\n    \n>       async for event in events:\n\nagent_trajectory/asset_management.py:24: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/langchain_core/runnables/base.py:1246: in astream_events\n    async for event in event_stream:\n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/langchain_core/tracers/event_stream.py:778: in _astream_events_implementation_v1\n    async for log in _astream_log_implementation(  # type: ignore[misc]\n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/langchain_core/tracers/log_stream.py:670: in _astream_log_implementation\n    await task\n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/langchain_core/tracers/log_stream.py:624: in consume_astream\n    async for chunk in runnable.astream(input, config, **kwargs):\n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/langchain/agents/agent.py:1595: in astream\n    async for step in iterator:\n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/langchain/agents/agent_iterator.py:246: in __aiter__\n    async for chunk in self.agent_executor._aiter_next_step(\n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/langchain/agents/agent.py:1360: in _aiter_next_step\n    result = await asyncio.gather(\n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/langchain/agents/agent.py:1393: in _aperform_agent_action\n    observation = await tool.arun(\n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/langchain_core/tools.py:747: in arun\n    raise error_to_raise\n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/langchain_core/tools.py:704: in arun\n    tool_args, tool_kwargs = self._to_args_and_kwargs(tool_input)\n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/langchain_core/tools.py:525: in _to_args_and_kwargs\n    tool_input = self._parse_input(tool_input)\n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/langchain_core/tools.py:478: in _parse_input\n    result = input_args.parse_obj(tool_input)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\ncls = <class 'openagent.executors.swap_executor.ParamSchema'>\nobj = {'amount': '20', 'from_chain': 'ETH', 'from_token': 'ETH', 'to_chain': 'eth', ...}\n\n    @classmethod\n    @typing_extensions.deprecated('The `parse_obj` method is deprecated; use `model_validate` instead.', category=None)\n    def parse_obj(cls, obj: Any) -> Self:  # noqa: D102\n        warnings.warn(\n            'The `parse_obj` method is deprecated; use `model_validate` instead.', category=PydanticDeprecatedSince20\n        )\n>       return cls.model_validate(obj)\nE       pydantic_core._pydantic_core.ValidationError: 1 validation error for ParamSchema\nE       to_chain\nE         Input should be 'ETH', 'BSC', 'ARBITRUM', 'OPTIMISM' or 'POLYGON' [type=literal_error, input_value='eth', input_type=str]\nE           For further information visit https://errors.pydantic.dev/2.8/v/literal_error\n\n/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/pydantic/main.py:1135: ValidationError"}, "attachments": [{"name": "stdout", "source": "d8ef57cb-bdb9-4143-b8ad-2d48e8958fe3-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "8716822d-c4c8-4613-93b0-b5ea8eacdea8-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "__pytest_repeat_step_number", "value": "2"}], "start": 1730429125932, "stop": 1730429159599, "uuid": "80e051b0-b497-4dd4-af8e-008858d08b61", "historyId": "20654169843db66fa35b9b68c4c90677", "testCaseId": "7874d2d5c6ca6245d9799c70e22647dc", "fullName": "tests.agent_trajectory.asset_management#test_swap_eth_to_usdt", "labels": [{"name": "tag", "value": "asyncio"}, {"name": "parentSuite", "value": "tests.agent_trajectory"}, {"name": "suite", "value": "asset_management"}, {"name": "host", "value": "fv-az1152-915"}, {"name": "thread", "value": "5844-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.agent_trajectory.asset_management"}]}